### ISSUE TITLE
Ubuntu 4.8.2 不支持cd -{N}？

### ISSUE THREAD

**Issue by openluopworld** [skywind3000/awesome-cheatsheets#10]
```sh
pushd ~/kernel-4.4
pushd ~/github
pushd ~/temp-file/jni-ce
```
luopeng@abcdef:~/temp-file/jni-ce
```sh
dirs -v
```
0  ~/temp-file/jni-ce
1  ~/github
2  ~/kernel-4.4
3  ~
```sh
cd -1
```
-sh: cd: -1: invalid option
```sh
cd -2
```
-sh: cd: -2: invalid option

**Comment by skywind3000** [comment]
你可以使用这个函数，把它 alias 成 cd 

https://github.com/skywind3000/vim/blob/28ab18e772363b0b343ba4c7987de35ad79f4f92/etc/function.sh#L28
