### ISSUE TITLE
添加安装脚本

### ISSUE THREAD

**Issue by alvisisme** [skywind3000/awesome-cheatsheets#13]
既然是速查表，需不需要做个命令行脚本工具什么的，类似终端输入`cheatsheet vim`, 直接把文件内容输出到终端上，代替man工具快速查询．一键更新什么的也方便．

**Comment by alvisisme** [comment]
找到类似工具了 https://github.com/chrisallenlane/cheat

**Comment by skywind3000** [comment]
还有 tldr python版本：

    pip install tldr

比 cheat 更好。

还有 bro 

    gem install bropages
