### ISSUE TITLE
建议格外均为MD

### ISSUE THREAD

**Issue by luckrill** [skywind3000/awesome-cheatsheets#44]
我有心转换格式到 MD，更为方便
速查表 相当需要，并且需要不断积累更多应用
现代编辑器 atom, vscode 也应该补上

**Comment by Joxos** [comment]
MD啊，我赞成。

**Comment by cupen** [comment]
附议!   章节效果会好看些,   repo 主若同意我就把 tmux 那个处理下.

**Comment by cupen** [comment]
@luckrill  需要加内容, 你可以提 pr .
