### ISSUE TITLE
想开个 curl 的分支啊，滋瓷不滋瓷啊

### ISSUE THREAD

**Issue by rthel** [skywind3000/awesome-cheatsheets#6]
把 curl 的man page 翻译一遍也不好，这个 curl 该怎么做才称得上是cheatsheet呢

**Comment by skywind3000** [comment]
1. 网上搜 curl 的中英文教程，确定大体结构，即分几个类别叙述

2. 安装：cheat, tldr, bropages 三套帮助系统

    pip install cheat
    pip install tldr
    gem install bropages

3. 分别在 man pages, info pages,  还有上面三个帮助系统里查看 curl 的帮助，并提炼对你有用的，填充进去。

4. 网上搜索 curl cheatsheet ，找出 1-3 分其他人做的 cheat sheet 再整合一下。

**Comment by skywind3000** [comment]
man pages / info pages 太饶舌了，看起来浪费时间，cheat, tldr, bropages 还有网上搜索的各种 cheatsheet 都是偏向用例的，针对性更强，man pages, info pages 是用来查缺补漏的。

**Comment by cnBruceHong** [comment]
把常用的加进来就可以了，追求精而不是全。

**Comment by zmdi998** [comment]
大神，这个可以分享连接别人的APP内容吗？

**Comment by skywind3000** [comment]
啥叫分享别人app连接内容？
